// Regenerates every derived brand asset from the single source of truth
// (assets/logo-on-white.svg): the transparent default SVG, the PNG ladders,
// and the src/logo.generated.ts string module.
//
// Run: bun run generate   (from packages/branding)

// eslint-disable-next-line import-x/no-extraneous-dependencies
import { Resvg } from '@resvg/resvg-js'
import { readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'

const pkgDir = join(import.meta.dir, '..')
const assetsDir = join(pkgDir, 'assets')
const srcDir = join(pkgDir, 'src')

// Source of truth: the raw Figma export (white background + bridge path).
const onWhite = (
  await readFile(
    join(assetsDir, 'logo-on-white.svg'),
    'utf8',
  )
).trim()

// Derive the transparent DEFAULT by removing the white background rect.
const transparent = onWhite
  .replace(
    /\s*<rect\b[^>]*\bfill="white"[^>]*\/>\s*/i,
    '\n',
  )
  .trim()

if (transparent === onWhite) {
  throw new Error(
    'logo-on-white.svg: white <rect> not found/stripped',
  )
}

// Extract geometry for React consumers (path data + viewBox).
const pathMatch = onWhite.match(
  /<path\b[^>]*\bd="([^"]+)"/i,
)
if (!pathMatch) {
  throw new Error(
    'logo-on-white.svg: no <path d="…"> found',
  )
}
const logoPath = pathMatch[1]

const viewBoxMatch = onWhite.match(/viewBox="([^"]+)"/i)
if (!viewBoxMatch) {
  throw new Error('logo-on-white.svg: no viewBox="…" found')
}
const logoViewBox = viewBoxMatch[1]

const color = '#D97757'

// Write the transparent default SVG file.
await writeFile(
  join(assetsDir, 'logo.svg'),
  `${transparent}\n`,
)

const rasterize = (svg: string, width: number) =>
  new Resvg(svg, {
    fitTo: { mode: 'width', value: width },
  })
    .render()
    .asPng()

// Transparent raster ladder (the default).
const transparentSizes = [16, 32, 48, 128, 256, 512, 1024]
for (const size of transparentSizes) {
  await writeFile(
    join(assetsDir, `logo-${size}.png`),
    rasterize(transparent, size),
  )
}

// White full-bleed tiles (Figma publish icon + GitHub avatar).
const tileSizes = [128, 256, 512]
for (const size of tileSizes) {
  await writeFile(
    join(assetsDir, `icon-${size}.png`),
    rasterize(onWhite, size),
  )
}

// Placeholder cover art (1920x1080, mark centered on white). This
// hardcodes the source's 1024-square viewBox and brand color as a
// standalone placeholder composition — it is intentionally not
// derived from logo-on-white.svg's own dimensions.
const scale = 480 / 1024
const coverSvg =
  '<svg width="1920" height="1080" viewBox="0 0 1920 1080" xmlns="http://www.w3.org/2000/svg">' +
  '<rect width="1920" height="1080" fill="#FFFFFF"/>' +
  `<g transform="translate(720 300) scale(${scale})">` +
  `<path d="${logoPath}" fill="${color}"/></g>` +
  '</svg>'
await writeFile(
  join(assetsDir, 'figma-cover-1920x1080.png'),
  rasterize(coverSvg, 1920),
)

// Emit the generated TS string module.
const generated =
  '/* eslint-disable */\n' +
  '// GENERATED by scripts/generate.ts — do not edit by hand.\n' +
  '// Source of truth: assets/logo-on-white.svg. Run `bun run generate`.\n\n' +
  `export const LOGO_SVG = ${JSON.stringify(transparent)}\n\n` +
  `export const LOGO_ON_WHITE_SVG = ${JSON.stringify(onWhite)}\n\n` +
  `export const LOGO_PATH = ${JSON.stringify(logoPath)}\n\n` +
  `export const LOGO_VIEWBOX = ${JSON.stringify(logoViewBox)}\n`
await writeFile(
  join(srcDir, 'logo.generated.ts'),
  generated,
)

console.log('branding: generated assets', {
  transparentSizes,
  tileSizes,
  cover: '1920x1080',
})
